name: adiletkz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # üåç –õ–æ–∫–∞–ª–∏–∑–∞—Ü–∏—è
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # üîß –û—Å–Ω–æ–≤–Ω—ã–µ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏
  http: ^1.2.2
  webview_flutter: ^4.13.0
  mask_text_input_formatter: ^2.4.1
  share_plus: ^10.0.0
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.3.2
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  pdf: ^3.10.4
  printing: ^5.11.2
  path_provider: ^2.1.2
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0
  url_launcher: ^6.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # ‚Üê –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –≤–∫–ª—é—á–∏ –≥–µ–Ω–µ—Ä–∞—Ü–∏—é –∫–æ–¥–∞

  assets:
    - lib/image/4568876876.jpg
    - .env



